# ---- 服务器 CUDA 训练使用 ----
FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-runtime

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    git \
    vim \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*

COPY . /workspace

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["/bin/bash"]